// import "./globals.css";
// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import Navbar from "@/components/ui/Navbar";
// import Footer from "@/components/ui/Footer";
// import { ThemeProvider } from "@/components/theme-provider"
// const inter = Inter({ subsets: ["latin"] });
// export const metadata: Metadata = {
//   title: "Aman Kohare",
//   description: "Generated by aman kohare",
//   icons: [
//     {
//       rel: "apple-touch-icon",
//       url: "/icon/logo.png",
//     },
//     {
//       rel: "icon",
//       type: "image/png",
//       sizes: "32x32",
//       url: "/icons/logo.png",
//     },
//     {
//       rel: "icon",
//       type: "image/png",
//       sizes: "16x16",
//       url: "/icons/logo.png",
//     },
//   ],
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <ThemeProvider
//           attribute="class"
//           defaultTheme="system"
//           enableSystem
//           disableTransitionOnChange>
//           <Navbar />
//           {children}
//           <Footer />
//         </ThemeProvider>
//       </body>
//     </html>
//   );
// }

import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/ui/Navbar";
import Footer from "@/components/ui/Footer";
import { ThemeProvider } from "@/components/theme-provider"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Aman Kohare",
  description: "Generated by Aman Kohare",
  icons: [
    {
      rel: "apple-touch-icon",
      url: "/icon/logo.png",
    },
    {
      rel: "icon",
      type: "image/png",
      sizes: "32x32",
      url: "/icons/logo.png",
    },
    {
      rel: "icon",
      type: "image/png",
      sizes: "16x16",
      url: "/icons/logo.png",
    },
  ],
  // SEO Meta Tags
  keywords: "web development, Aman Kohare, Next.js, React, portfolio, developer ,React native",
  authors: [{ name: "Aman Kohare", url: "https://helloaman.vercel.app/" }],
  robots: "index, follow",
  viewport: "width=device-width, initial-scale=1",
  // Open Graph Meta Tags for better social media sharing
  openGraph: {
    title: "Aman Kohare",
    description: "Welcome to Aman Kohare's personal website.",
    url: "https://helloaman.vercel.app/",
    siteName: "Aman Kohare",
    images: [
      {
        url: "/icon/logo.png",
        width: 1200,
        height: 630,
        alt: "Aman Kohare",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Aman Kohare",
    description: "Welcome to Aman Kohare's personal website.",
    images: ["/icons/logo.png"],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange>
          <Navbar />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
